# Generated by Django 4.2.7 on 2024-02-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grocerylist", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecipeList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("servingsize", models.IntegerField()),
                ("ingredients_list", models.CharField(max_length=255)),
                ("directions", models.CharField(max_length=1000)),
            ],
        ),
    ]
