# Generated by Django 4.2.7 on 2024-02-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grocerylist", "0002_recipelist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipelist",
            name="servingsize",
            field=models.CharField(max_length=10),
        ),
    ]
