# Generated by Django 4.2.11 on 2024-03-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerylist', '0003_alter_recipelist_servingsize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocerylist',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
