# Generated by Django 4.2.9 on 2024-04-21 00:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grocerylist", "0005_citylist"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=255)),
                ("zip", models.IntegerField()),
            ],
        ),
    ]
