# Generated by Django 4.2.9 on 2024-04-21 01:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grocerylist", "0006_storelist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storelist",
            name="zip",
            field=models.CharField(max_length=255),
        ),
    ]
