# Generated by Django 4.2.9 on 2024-04-21 02:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grocerylist", "0007_alter_storelist_zip"),
    ]

    operations = [
        migrations.RenameField(
            model_name="grocerylist",
            old_name="rating",
            new_name="description",
        ),
        migrations.AddField(
            model_name="grocerylist",
            name="imagelink",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="grocerylist",
            name="quantity",
            field=models.CharField(default="1", max_length=255, null=True),
        ),
    ]
