# Generated by Django 4.2.9 on 2024-04-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grocerylist", "0009_storelist_imagelink"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipelist",
            name="imagelink",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="recipelist",
            name="recipelink",
            field=models.URLField(null=True),
        ),
    ]
